### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by ImaginaryTraveller** [Grisgram/gml-outline-shader-drawer#4]
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object OutlineObjectBaked:

Canvas Error: Canvas has no data or in use!
 at gml_Script___CanvasError (line 3) -        show_error("Canvas Error: " + _str, true);
############################################################################################
gml_Script___CanvasError (line 3)
gml_Script_anon_Canvas_gml_GlobalScript_Canvas_25410_Canvas_gml_GlobalScript_Canvas (line 869) -                             __CanvasError("Canvas has no data or in use!");              
gml_Script_anon_Canvas_gml_GlobalScript_Canvas_19934_Canvas_gml_GlobalScript_Canvas (line 701) -                      __validateContents();
gml_Script_anon_CanvasSprite_gml_GlobalScript_sprite_to_canvas_2324_CanvasSprite_gml_GlobalScript_sprite_to_canvas (line 59) -               canvas.DrawPart(subimages[@ frame], 0, image_width, image_height, xp - xoffset, yp - yoffset);
gml_Script_anon_gml_Object_OutlineObjectBaked_Create_0_1485_gml_Object_OutlineObjectBaked_Create_0 (line 46) -               canvas.draw_frame(image_index, x - outline_strength - TEXTURE_PAGE_BORDER_SIZE, y - outline_strength - TEXTURE_PAGE_BORDER_SIZE);
gml_Object_OutlineObjectBaked_Draw_0 (line 4) - self.__draw();
gml_Object_obj_shootable_Draw_0 (line 6)

things run fine in demo project but i have no idea why it crashes when i import it to mine

**Comment by Epicwindows** [comment]
i think i fixed that but now i have another issue where the game crashes if i change window size mid game

**Comment by ImaginaryTraveller** [comment]
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object OutlineObjectBaked:

Trying to use non-existing surface.
 at gml_Script_anon_Canvas_gml_GlobalScript_Canvas_19934_Canvas_gml_GlobalScript_Canvas (line 703) -                      draw_surface_part(__surface, _left, _top, _width, _height, _x, _y);
############################################################################################
gml_Script_anon_Canvas_gml_GlobalScript_Canvas_19934_Canvas_gml_GlobalScript_Canvas (line 703)
gml_Script_anon_CanvasSprite_gml_GlobalScript_sprite_to_canvas_2324_CanvasSprite_gml_GlobalScript_sprite_to_canvas (line 59) -               canvas.DrawPart(subimages[@ frame], 0, image_width, image_height, xp - xoffset, yp - yoffset);
gml_Script_anon_gml_Object_OutlineObjectBaked_Create_0_1442_gml_Object_OutlineObjectBaked_Create_0 (line 45) -               canvas.draw_frame(image_index, x - outline_strength - TEXTURE_PAGE_BORDER_SIZE, y - outline_strength - TEXTURE_PAGE_BORDER_SIZE);
gml_Object_OutlineObjectBaked_Draw_0 (line 4) - self.__draw();
gml_Object_obj_shootable_Draw_0 (line 21)


https://cdn.discordapp.com/attachments/945992267204796427/1107998019040849953/2023-05-16_19-47-01.mp4

**Comment by Grisgram** [comment]
Hey there -- the second one is very interesting.
Please let me investigate -- I'll be back with info shortly (after work this evening I can take a look)

**Comment by ImaginaryTraveller** [comment]
thanks for the compiment

i just resized the window by clicking the windows square button on top right(dragging cornors)

**Comment by Grisgram** [comment]
Heya,

https://github.com/Grisgram/gml-outline-shader-drawer/releases/tag/2.1

Please try the updated version and let me know how it goes!

**Comment by ImaginaryTraveller** [comment]
everything seems fine so far
thanks for the fix 🙏

**Comment by Grisgram** [comment]
any time! spread the word, so this lib gets bigger reach :-)
